# Generated by Django 2.0.6 on 2018-07-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=24)),
                ('date_publish', models.DateTimeField(auto_now=True)),
                ('click_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article_comment',
            name='comment_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='comment_content',
            field=models.ManyToManyField(through='blogapp.Article_Comment', to='blogapp.Comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Category'),
        ),
    ]
