# Generated by Django 2.0.6 on 2018-07-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
    ]
