# Generated by Django 2.0.6 on 2018-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='describe',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
