# Generated by Django 2.0.6 on 2018-07-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_article_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('articles', models.ManyToManyField(through='blogapp.Articles_Label', to='blogapp.Article')),
            ],
        ),
        migrations.AddField(
            model_name='articles_label',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Label'),
        ),
    ]
